# This file tells Render how to build and run your application.
services:
  # A web service
  - type: web
    name: python-quiz-game
    # The runtime environment for your service
    env: python
    # The command to install dependencies
    buildCommand: "pip install -r requirements.txt"
    # The command to start your web server
    startCommand: "gunicorn app:app"
